### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/tauri-vite-example#2]
- [x] `PKGBUILD`
  - fixed in https://github.com/hi-ogawa/tauri-vite-example/pull/1
- [ ] ci
  - https://github.com/tauri-apps/tauri-action
- [x] rust IDE experience (maybe just put root `Cargo.toml`? https://github.com/hi-ogawa/tauri-vite-example/pull/3)
- [x] browser debugging (aka devtool)
  - usual `Control-Shift-I` works
- [ ] IPC with rust
  - event from rust to browser?
- [ ] web ui for https://github.com/hi-ogawa/pipewire_graph_egui
  - https://github.com/wbkd/react-flow
  - maybe just use `pw-dump`, `pw-link`, commands
  - https://github.com/hi-ogawa/tauri-vite-example/pull/4
